"""empty message

Revision ID: 7f1f8d73732f
Revises: 
Create Date: 2021-03-24 20:31:52.859832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1f8d73732f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_name'), 'object', ['name'], unique=False)
    op.create_index(op.f('ix_object_path'), 'object', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_path'), table_name='object')
    op.drop_index(op.f('ix_object_name'), table_name='object')
    op.drop_table('object')
    # ### end Alembic commands ###
